export let drugs = [
  {
    id: 1,
    name: "Enzianwurzel",
    type: "Wurzel",
    category: "Wurzeln",
    family: "Enziangewächse",
    origin: "Hochgebirge Europas",
    ingredients: [
      "bis 30% Gentianose (vergä. Dreifachzucker)",
      "Gentin (gelber Farbstoff)",
      "Gentiopikrin (Bitterstoff)",
      "Amarogentin (Bitterstoff)",
      "Pektine",
      "6% fettes Öl",
    ],
    treatment: "Extraktionsverfahren",
    use: [
      "Alpenkräuterlikör",
      "Abteilikör",
      "Boonekamp",
      "Feinbitter",
      "Halb und Halb",
    ],
    note: "Eine typische Bitterstoffdroge, die magenberuhigend und verdauungsfördernd wirkt. Wurde früher als Fiebermittel eingesetz.",
    img: "enzianwurzel.png",
  },
  {
    id: 2,
    name: "Angelikawurzel",
    type: "Wurzel",
    category: "Wurzeln",
    family: "Doldengewächse",
    origin: "Europa, China, Rußland",
    ingredients: [
      "1% ätherisches Öl (Angelikaöl)",
      "Bitterstoffe",
      "Gerbstoffe",
      "bis 6% Harz",
      "Säuren (Baldriansäure, Angelikasäure)",
      "bis 24% Zucker",
      "Wachse",
    ],
    treatment: ["Extraktionsverfahren", "Destillation (wird feiner)"],
    use: [
      "Altbitter",
      "Alpenkräuterlikör",
      "Angostura",
      "Boonekamp",
      "Stonsdorfer",
    ],
    note: "Früher eines der wichtigsten Heilkräuter. Ein Magenmittel bei Koliken. Wirkt gegen Flatulenzen.",
    img: "angelikawurzel.png",
  },
  {
    id: 3,
    name: "Süßholzwurzel",
    type: "Wurzel",
    category: "Wurzeln",
    family: "Hülsenfruchtgewächse",
    origin: "Südeuropa, Nordafrika, Südasien",
    ingredients: [
      "7% Glycyrrhizinsäure (stark süß)",
      "Stärke",
      "Bitterstoffe",
      "bis 23% Zucker",
      "Mannit",
      "Farbstoff (gelb)",
      "Cumarin",
    ],
    treatment: ["Extraktionsverfahren"],
    use: [
      "Alpenkräuterlikör",
      "Angostura",
      "Boonekamp",
      "Pastis",
      "Stonsdorfer",
    ],
    note: "Der eingedickte Saft wird zu Lakritz gepresst. Beschleunig die Heilung bei Magengeschwüren. Durch Zugabe von Ammoniumchlorid ensteht Salmiak. \nKennzeichnung auf Spirituosen: \n - 10 bis 290 mg/l -> 'Enthält Süßholz' \n - ab 300 mg/l -> 'Enthält Süßholz - bei hohem Blutdruck sollte ein übermäßiger Verzehr dieses Erzeugnisses vermieden werden'",
    img: "suessholzwurzel.png",
  },
  {
    id: 4,
    name: "Chinarinde",
    type: "Rinde",
    category: "Rinden",
    family: "Rötegewächse",
    origin: "Ostindien, Java, Sri Lanka, Jamaika",
    ingredients: [
      "ätherisches Öl",
      "3 - 18% Alkaloide: Chinin (bis 13%), Chinidrin (bis 4%), Chinchonin bis 8%",
      "Chinasäure",
      "Gerbsäuren",
      "Chinovin",
      "Harze",
    ],
    treatment: ["Extraktionsverfahren"],
    use: [
      "Alpenkräuterlikör",
      "Angostura",
      "Chinabitter",
      "Halb und Halb",
      "Stonsdorfer",
    ],
    note: "Wurde früher gegen Malaria und Wadenkrämpfe verwendet. Ist eine typische Bitterstoffdroge und wirkt verdauungsfördernd und appetitanregend.",
    img: "chinarinde.png",
  },
];
